version: '3'
services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile-node
    ports:
      - "3000:3000"
    networks:
      - website

  nginx-proxy:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "80:80"
    depends_on:
      - node-app
    networks:
      - website

networks:
  website:
