name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t consultancy_site .
      
    - name: Tag Image
      run: docker tag consultancy_site lipprossconsultancy.azurecr.io/consultancy/site:latest

    - name: Login to ACR
      run: | 
        az login --service-principal -u ${{ secrets.ARM_CLIENT_ID }} -p ${{ secrets.ARM_CLIENT_SECRET }} --tenant ${{ secrets.ARM_TENANT_ID }}
        az acr login --name lipprossconsultancy

    - name: Push to ACR
      run: docker push lipprossconsultancy.azurecr.io/consultancy/site:latest
      
