name: 'Terraform CI/CD'

on:
  push:
    paths: 
      - terraform/**
    branches:
      - main
  pull_request:
    paths: 
      - terraform/**
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    env:
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
    - uses: actions/checkout@v2

    - name: Print ARM_SUBSCRIPTION_ID
      run: echo "Subscription ID length is ${#ARM_SUBSCRIPTION_ID}"

    - name: 'Setup Terraform'
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: 'Terraform Init'
      run: terraform init
      working-directory: ./terraform

    - name: 'Terraform Validate'
      run: terraform validate
      working-directory: ./terraform

    - name: 'Terraform Plan'
      run: terraform plan
      working-directory: ./terraform

    - name: 'Terraform Apply'
      run: terraform apply -auto-approve
      working-directory: ./terraform
